In [2]:
import numpy as np
a=([111,112,113,114,115,116]),([1,2,3,4,5,6])
arr=np.array(a)
print(arr)

[[111 112 113 114 115 116]
 [  1   2   3   4   5   6]]


In [3]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
import numpy as np
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.shape)
print(arr.dtype)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
2
12
(3, 4)
int32


In [5]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[11,12,13,14],[15,16,17,18]])
arr3=np.concatenate([arr1,arr2])
print(arr3)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]


In [9]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
arr2=np.array([[11,12,13,14],[15,16,17,18]])
print(arr1+arr2)
print()
print(arr1-arr2)
print(arr)
print(arr1*arr2)
print(arr)
print(arr1//arr2)
print(arr)
print(arr1%arr2)
print(arr)
print(arr1/arr2)
print(arr)

[[12 14 16 18]
 [20 22 24 26]]

[[-10 -10 -10 -10]
 [-10 -10 -10 -10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 11  24  39  56]
 [ 75  96 119 144]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 0 0 0]
 [0 0 0 0]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0.09090909 0.16666667 0.23076923 0.28571429]
 [0.33333333 0.375      0.41176471 0.44444444]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
import numpy as np
a=[11,12,13,14,15,16,17,18,19,20]
arr=np.array(a)
print(arr[arr<18])
print(arr[arr%2==1])

[11 12 13 14 15 16 17]
[11 13 15 17 19]


In [11]:
import numpy as np
x=np.zeros(3)
y=np.ones(2)
print(y)

[1. 1.]


In [12]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)
print()
arr2=np.array([[11,12,13,14],[15,16,17,18]])
print(arr2)
print()
arr3=np.concatenate([arr1,arr2],axis=0)
arr4=np.concatenate([arr1,arr2],axis=1)
print(arr3)
print(arr4)

[[1 2 3 4]
 [5 6 7 8]]

[[11 12 13 14]
 [15 16 17 18]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]
[[ 1  2  3  4 11 12 13 14]
 [ 5  6  7  8 15 16 17 18]]


In [13]:
import numpy as np
arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(np.max(arr1))
print(np.min(arr1))
print(np.sum(arr1))
print(np.std(arr1))
print(np.var(arr1))
print(np.mean(arr1))
print(np.median(arr1))

8
1
36
2.29128784747792
5.25
4.5
4.5


In [14]:
import numpy as np
a=([[111,112],[113,114]])
arr1=np.array(a)
print(arr1)
arr2=np.array([[11,12],[15,16]])
print(arr2)
print()
print(np.linalg.matrix_rank(arr1),"\n")
print(np.linalg.matrix_rank(arr2))
print(np.linalg.inv(arr1))
print(np.linalg.det(arr1))
print(np.linalg.eig(arr1))
print(np.dot(arr1,arr2))
print(np.cross(arr1,arr2))


[[111 112]
 [113 114]]
[[11 12]
 [15 16]]

2 

2
[[-57.   56. ]
 [ 56.5 -55.5]]
-2.0000000000003553
(array([-8.88853775e-03,  2.25008889e+02]), array([[-0.71024234, -0.70079395],
       [ 0.70395726, -0.71336375]]))
[[2901 3124]
 [2953 3180]]
[100  98]
